#OPTIONS

# Prefix
jobid: "job_prefix"
# Input Files
REFIN: "data/assembly.fasta" #location of assembly to cluster
RAW_SR: "data/" #location of timepoint raw reads
samples: "samples.tsv"
in_file_extension: "fastq.gz" #extension of timepoint files
# Method of mapping required
mapping: "LR" # SR, paired_SR or LR
#Database locations
blastdb: "/mnt/lustre/groups/biol-chong-2019/databases/blast/nt/nt"
checkm_db_root: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
krakendb: "/mnt/lustre/groups/biol-chong-2019/databases/krakendb/kraken2_samstudio8/"


# Clustering options
CONTIG_T: "1000"
P_THRESH: "0.997"
meth_counts: "norm" # norm or raw
# Output plot properties
kraken_level: "F" # Taxonomic level used in output plots (F, G, S etc.)
date_scale: "n" # Plot timepoints in plot using date scale (if provided)
plot_order: "kraken_id kraken_per tot_len"
