jobid: "NAB_new"
REFIN: "data/yw_polished_anvio.fasta"
CONTIG_T: "1000"
P_THRESH: "0.997"
krakendb: "/mnt/lustre/groups/biol-chong-2019/databases/krakendb/kraken2_samstudio8/"
kraken_level: "F"
samples: "samples.tsv"
RAW_SR: "data/"
date_scale: "y"
