jobid: "NAB_997_new"
REFIN: "data/yw_polished_anvio.fasta"
CONTIG_T: "1000"
P_THRESH: "0.997"
krakendb: "/mnt/lustre/groups/biol-chong-2019/databases/krakendb/kraken2_samstudio8/"
kraken_level: "F"
samples: "samples.tsv"
RAW_SR: "data/"
date_scale: "y"
blastdb: "/mnt/lustre/groups/biol-chong-2019/databases/blast/nt/nt"
in_file_extension: "fastq.gz"
checkm_db_root: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
