# Prefix
JOBID: "snake_split_bin"
# Input Files
#Location of samples tsv
SAMPLES: "config/samples.tsv"
#location of assembly to cluster
REFIN: "data/canu10_med.fasta"
#location of timepoint raw reads
RAW_DIR: "data/"
#extension of timepoint files
FILE_EX: "fastq"
# Method of mapping required
MAPPING: "LR" # SR, paired_SR or LR
# Clustering options
CONTIG_T: "1000"
P_THRESH: "0.997"
COUNT_METHOD: "norm" # norm or raw

CHECKM_DB: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
