#OPTIONS

# Prefix
jobid: "snake_v5.6.0"
# Input Files
REFIN: "data/canu10_med.fasta" #location of assembly to cluster
RAW_DIR: "data/" #location of timepoint raw reads
samples: "samples.tsv"
in_file_extension: "fastq" #extension of timepoint files
# Method of mapping required
mapping: "LR" # SR, paired_SR or LR
#Database locations
blastdb: "/mnt/lustre/groups/biol-chong-2019/databases/blast/nt/nt"
checkm_db_root: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
krakendb: "/mnt/lustre/groups/biol-chong-2019/databases/krakendb/kraken2_samstudio8/"
GTDB: "Y" # Y/N if the kraken DB is based on GTDB taxonomy, adds NCBI comparison to output

# Clustering options
CONTIG_T: "1000"
P_THRESH: "0.997"
meth_counts: "norm" # norm or raw

# Output plot properties
kraken_level: "F" # Taxonomic level used in output plots (F, G, S etc.)
date_scale: "n" # Plot timepoints in plot using date scale (if provided)
plot_order: "tot_len" # Statistics to order the output plot by, options = 'no_seq','tot_len','av_cov','sd_cov', 'av_gc','sd_gc','n_50','comp', 'contam', 'kraken_id', 'kraken_per', 'gtdb_ncbi'
