#OPTIONS
blastdb: "/mnt/lustre/groups/biol-chong-2019/databases/blast/nt/nt"
checkm_db_root: "/mnt/lustre/groups/biol-chong-2019/databases/checkm_data"
krakendb: "/mnt/lustre/groups/biol-chong-2019/databases/krakendb/kraken2_samstudio8/"
GTDB: "Y" # Y/N if the kraken DB is based on GTDB taxonomy, adds NCBI comparison to output
# Output plot properties
kraken_level: "F" # Taxonomic level used in output plots (F, G, S etc.)
date_scale: "n" # Plot timepoints in plot using date scale (if provided)
plot_order: "tot_len" # Statistics to order the output plot by, options = 'no_seq','tot_len','av_cov','sd_cov', 'av_gc','sd_gc','n_50','comp', 'contam', 'kraken_id', 'kraken_per', 'gtdb_ncbi'

JOBID: "snake_split_bin"
REFIN: "data/canu10_med.fasta"
BIN_LOC: "results/clusters/"
